// <auto-generated />
using System;
using InteractiveScreenDashboard.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InteractiveScreenDashboard.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InteractiveScreenDashboard.Data.Models.Driver", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Liecense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vehicleid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Vehicleid");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("InteractiveScreenDashboard.Data.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountTypeId = 1,
                            CompanyId = 0,
                            Name = "Vivian",
                            Password = "Tester@123",
                            UserName = "vtharaka@routesme.com"
                        },
                        new
                        {
                            Id = 2,
                            AccountTypeId = 2,
                            CompanyId = 0,
                            Name = "Yahya",
                            Password = "Tester@123",
                            UserName = "yshaar@routesme.com"
                        });
                });

            modelBuilder.Entity("InteractiveScreenDashboard.Data.Models.Users", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_role_id1")
                        .HasColumnType("int");

                    b.HasKey("User_id");

                    b.HasIndex("User_role_id1");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_id = 1,
                            Email = "yshaar@routesme.com",
                            First_name = "Yahya",
                            Last_name = "A",
                            Password = "Tester@123",
                            User_role_id1 = 1
                        },
                        new
                        {
                            User_id = 2,
                            Email = "vtharaka@routesme.com",
                            First_name = "Vivian",
                            Last_name = "George",
                            Password = "Tester@123",
                            User_role_id1 = 1
                        });
                });

            modelBuilder.Entity("InteractiveScreenDashboard.Data.Models.Vehicle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("plate")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("InteractiveScreenDashboard.Data.Models.user_roles", b =>
                {
                    b.Property<int>("User_role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_role_id");

                    b.ToTable("User_Roles");

                    b.HasData(
                        new
                        {
                            User_role_id = 1,
                            Name = "SuperUser"
                        });
                });

            modelBuilder.Entity("InteractiveScreenDashboard.Data.Models.Driver", b =>
                {
                    b.HasOne("InteractiveScreenDashboard.Data.Models.Vehicle", "OwnedVehicles")
                        .WithMany()
                        .HasForeignKey("Vehicleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InteractiveScreenDashboard.Data.Models.Users", b =>
                {
                    b.HasOne("InteractiveScreenDashboard.Data.Models.user_roles", "User_role_id")
                        .WithMany()
                        .HasForeignKey("User_role_id1");
                });
#pragma warning restore 612, 618
        }
    }
}
